OGN:
  ssssssimulator: //Users/richard/Documents/Helios/log/log-gezc-ehtl-11-08.txt
  aprsServer: "aprs.glidernet.org"
  aprsPort: 14580
  aprsUser: "GEZC-EHTL"
  aprsFilter: 'r/52.06/5.94/15'

Helios:
  url: ""
  username: ''
  password: ''
  token: ''

Vliegveld:
  code: 'EHTL'
  hoogte: 80
  Banen:
    - code: '22R'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL t-strip.json'
    - code: '04L'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL t-strip.json'
    - code: '30R'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL t-strip.json'
    - code: '12'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL t-strip.json'
    - code: '04C'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 04C-22C.json'
    - code: '22C'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 04C-22C.json'
    - code: '04R'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 04R-22L.json'
    - code: '22L'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 04R-22L.json'
    - code: '14R'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 14R-32L.json'
    - code: '32L'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 14R-32L.json'
    - code: '14L'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 14L-32R.json'
    - code: '32R'
      GeoJSON: '/Users/richard/Documents/Flarm.js/EHTL 14L-32R.json'