/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Vliegtuigen/CreateTable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creeer database objecten */
        post: {
            parameters: {
                query: {
                    /** @description Dummy records aanmaken */
                    FILLDATA: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aangemaakt, Tabel toegevoegd */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv omdat de tabel al bestaat */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Vliegtuigen/CreateViews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creeer database views */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aangemaakt, View toegevoegd */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, view niet aangemaak */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Vliegtuigen/GetObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Haal een enkel vliegtuig op uit de database */
        get: {
            parameters: {
                query: {
                    /** @description Database ID van het vliegtuig record */
                    ID: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, data succesvol opgehaald */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ref_vliegtuigen"];
                    };
                };
                /** @description Data niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Methode niet toegestaan, input validatie error */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet aanvaardbaar, input ontbreekt */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Vliegtuigen/GetObjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Haal een lijst met vliegtuigen op uit de database. Query parameters worden in AND conditie gebruikt */
        get: {
            parameters: {
                query?: {
                    /** @description Database ID van het aanwezig record */
                    ID?: number;
                    /** @description Toon welke records verwijderd zijn. Default = false */
                    VERWIJDERD?: boolean;
                    /** @description Laatste aanpassing op basis van records in dataset. Bedoeld om data verbruik te verminderen. Dataset is daarom leeg */
                    LAATSTE_AANPASSING?: boolean;
                    /** @description HASH van laatste GetObjects aanroep. Indien bij nieuwe aanroep dezelfde data bevat, dan volgt http status code 304. In geval dataset niet hetzelfde is, dan komt de nieuwe dataset terug. Ook bedoeld om dataverbruik te vermindereren. Er wordt alleen data verzonden als het nodig is. */
                    HASH?: string;
                    /** @description Sortering van de velden in ORDER BY formaat. Default = CLUBKIST DESC, VOLGORDE, REGISTRATIE */
                    SORT?: string;
                    /** @description Maximum aantal records in de dataset. Gebruikt in LIMIT query */
                    MAX?: number;
                    /** @description Eerste record in de dataset. Gebruikt in LIMIT query */
                    START?: number;
                    /** @description Welke velden moet opgenomen worden in de dataset */
                    VELDEN?: string;
                    /** @description Zoek in de REGISTRATIE, CALLSIGN, FLARM_CODE */
                    SELECTIE?: string;
                    /** @description Een of meerdere vliegtuig database IDs in CSV formaat. AND conditie als er geen andere parameters zijn, anders OR conditie */
                    IN?: string;
                    /** @description Zoek op een of meerder type vliegtuig(en). Types als CSV formaat */
                    TYPES?: string;
                    /** @description Zoek op zitplaatsen 1/2 */
                    ZITPLAATSEN?: number;
                    /** @description Haal alle clubvliegtuigen op */
                    CLUBKIST?: boolean;
                    /** @description Haal alle zelfstarters op. */
                    ZELFSTART?: boolean;
                    /** @description Haal alle sleepkisten op. */
                    SLEEPKIST?: boolean;
                    /** @description Haal alle TMGs op. */
                    TMG?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK, data succesvol opgehaald */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["view_vliegtuigen"];
                    };
                };
                /** @description Data niet gemodificeerd, HASH in aanroep == hash in dataset */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Methode niet toegestaan, input validatie error */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Vliegtuigen/DeleteObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Markeer record als verwijderd. */
        delete: {
            parameters: {
                query: {
                    /** @description Database ID van het vliegtuig record. Meerdere ID's in CSV formaat */
                    ID: string;
                    /** @description Controleer of record bestaat voordat het verwijderd wordt. Default = true */
                    VERIFICATIE?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vliegtuig verwijderd */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet geautoriseerd, geen schrijfrechten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Methode niet toegestaan, input validatie error */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet aanvaardbaar, input ontbreekt */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Vliegtuigen/RestoreObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Record dat verwijderd is terug halen. VERWIJDERD marker krijgt reset */
        patch: {
            parameters: {
                query: {
                    /** @description Database ID van het record. Meerdere ID's in CSV formaat */
                    ID: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Record(s) hersteld */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet geautoriseerd, geen schrijfrechten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Methode niet toegestaan, input validatie error */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet aanvaardbaar, input ontbreekt */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/Vliegtuigen/SaveObject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update bestaand vliegtuig */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Vliegtuig data */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ref_vliegtuigen_in"];
                };
            };
            responses: {
                /** @description OK, data succesvol aangepast */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ref_vliegtuigen"];
                    };
                };
                /** @description Niet geautoriseerd, geen schrijfrechten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Methode niet toegestaan, input validatie error */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet aanvaardbaar, input ontbreekt */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict, registratie bestaat al */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Voeg nieuw vliegtuig toe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Vliegtuig data */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ref_vliegtuigen_in"];
                };
            };
            responses: {
                /** @description OK, data succesvol toegevoegd */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ref_vliegtuigen"];
                    };
                };
                /** @description Niet geautoriseerd, geen schrijfrechten */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Methode niet toegestaan, input validatie error */
                405: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Niet aanvaardbaar, input ontbreekt */
                406: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict, registratie bestaat al */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Data verwerkingsfout, bijv onjuiste veldwaarde (string ipv integer) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ref_vliegtuigen_in: {
            /**
             * Format: int32
             * @description Database ID van het vliegtuig record
             * @example 12871
             */
            ID?: number;
            /**
             * @description Het registratie nummer van het vliegtuig
             * @example PH-1234
             */
            REGISTRATIE?: string;
            /**
             * @description Optioneel het callsign van het vliegtuig
             * @example AA
             */
            CALLSIGN?: string;
            /**
             * @description De flarmcode zoals deze wordt uitgezonden. Zo kunnen we ontvangen flarm data herleiden naar een vliegtuig uit de database
             * @example 123456
             */
            FLARMCODE?: string;
            /**
             * Format: int32
             * @description Het aantal zitplaatsen. Is 1 of 2.
             * @example 1
             */
            ZITPLAATSEN?: number;
            /**
             * @description Kan het vliegtuig op eigen kracht starten.
             * @example 0
             */
            ZELFSTART?: boolean;
            /**
             * @description Is het een club vliegtuig?
             * @example 1
             */
            CLUBKIST?: boolean;
            /**
             * @description Is het een TMG?
             * @example 0
             */
            TMG?: boolean;
            /**
             * @description Is het een sleepvliegtuig?
             * @example 0
             */
            SLEEPKIST?: boolean;
            /**
             * @description Wordt vliegtuig ingezet voor DBO opleiding
             * @example 1
             */
            TRAINER?: boolean;
            /**
             * Format: int32
             * @description Link naar vliegtuig type tabel. Alleen nodig voor clubvliegtuigen
             * @example 12
             */
            TYPE_ID?: number;
            /**
             * Format: int32
             * @description Volgorde van vliegtuiglijst, bedoeld voor club vliegtuigen
             * @example 12
             */
            VOLGORDE?: number;
            /**
             * @description Mag het vliegtuig vliegen?
             * @example 1
             */
            INZETBAAR?: boolean;
            /**
             * @description URL naar het handboek
             * @example 1
             */
            URL?: string;
            /**
             * Format: int32
             * @description Link naar comptentie om met deze kist lokaal te vliegen
             */
            BEVOEGDHEID_LOKAAL_ID?: number;
            /**
             * Format: int32
             * @description Link naar comptentie om met deze kist overland te vliegen
             */
            BEVOEGDHEID_OVERLAND_ID?: number;
            /**
             * @description De opmerkingen die ingevoerd zijn
             * @example Radio stoort bij snelheid boven 150 km/h
             */
            OPMERKINGEN?: string;
        };
        ref_vliegtuigen: components["schemas"]["ref_vliegtuigen_in"] & {
            /**
             * @description Is dit record gemarkeerd als verwijderd?
             * @example 0
             */
            VERWIJDERD?: boolean;
            /**
             * Format: date-time
             * @description Tijdstempel van laaste aanpassing in de database
             * @example 2020-03-03 17:14:50Z
             */
            LAATSTE_AANPASSING?: string;
        };
        view_vliegtuigen_dataset: components["schemas"]["ref_vliegtuigen"] & {
            /**
             * @description Beschrijving van het vliegtuig type
             * @example Discus CS
             */
            VLIEGTUIGTYPE?: string;
            /**
             * @description Vliegtuig registratie en callsign
             * @example PH-1076 (E2)
             */
            REG_CALL?: string;
            /** @description Omschrijving van lokale bevoegdheid */
            BEVOEGDHEID_LOKAAL?: string;
            /** @description Omschrijving van overland bevoegdheid */
            BEVOEGDHEID_OVERLAND?: string;
        };
        view_vliegtuigen: {
            /**
             * Format: int32
             * @description Aantal records dat voldoet aan de criteria in de database
             * @example 287
             */
            totaal?: number;
            /**
             * Format: date-time
             * @description Tijdstempel van laaste aanpassing in de database van de records dat voldoet aan de criteria
             * @example 2020-02-12 21:15:16
             */
            laatste_aanpassing?: string;
            /**
             * @description hash van de dataset
             * @example 400000f
             */
            hash?: string;
            /** @description De dataset met records */
            dataset?: components["schemas"]["view_vliegtuigen_dataset"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
